version: "3"
services:
  backend-green:
    image: ${DOCKER_USERNAME}/kwak-doo-chul
    volumes:
      - /home/ubuntu/logs/:/logs/
    environment:
      - SPRING_PROFILES_ACTIVE

networks:
  default:
    name: kwakdoochul-network
    external: true
