version: "3"
services:
  backend-blue:
    image: ${DOCKER_USERNAME}/kwak-doo-chul
    volumes:
      - /home/ubuntu/logs/:/logs/
    environment:
      - SPRING_PROFILES_ACTIVE
    ports:
      - "8080:8080" 
networks:
  default:
    name: kwakdoochul-network
    external: true
