#spring.datasource.url=jdbc:mysql:mem:testdb;MODE=MySQL;
spring.datasource.url=jdbc:mysql://localhost:3306/capd?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
server.shutdown= graceful
spring.lifecycle.timeout-per-shutdown-phase= 10s
fcm.certification.path=kwakdoochul-bbb43-firebase-adminsdk-oyokf-f075393454.json
bucket.plan=test
token.uri=uri
redirect.uri=uri
grant.type=authorization_code
client.id=id
management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true
server.tomcat.mbeanregistry.enabled=true