name: Run Docker Compose

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, donggle-dev]
    steps:
      - uses: actions/checkout@v3
      - name: create .env
        run: |
          touch .env
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
      ## deploy to production
      - name: Deploy to prod
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo chmod +x deploy.sh
          sudo ./deploy.sh
          sudo docker image prune -af
